[versions]
groovy = "2.4.21"
groovy-cps = "4177.vb_203fe395445"
pipeline-groovy-lib = "798.v5cc688825312"
pipeline-unit = "1.29"
junit = "6.0.1"
codenarc = "3.6.0"
jakarta-servlet = "5.0.0"
jenkins = "2.568.3"
jenkins-bom = "7046.v43536164769c"
jenkins-test-harness = "2582.v92781333ea_78"

[libraries]
groovy = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
groovy-cps = { module = "com.cloudbees:groovy-cps", version.ref = "groovy-cps" }
pipeline-unit = { module = "com.lesfurets:jenkins-pipeline-unit", version.ref = "pipeline-unit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
codenarc = { module = "org.codenarc:CodeNarc", version.ref = "codenarc" }
jakarta-servlet-api = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-servlet" }
jenkins-bom = { module = "io.jenkins.tools.bom:bom-2.568.x", version.ref = "jenkins-bom" }
jenkins-core = { module = "org.jenkins-ci.main:jenkins-core", version.ref = "jenkins" }
jenkins-test-harness = { module = "org.jenkins-ci.main:jenkins-test-harness", version.ref = "jenkins-test-harness" }
jenkins-war = { module = "org.jenkins-ci.main:jenkins-war", version.ref = "jenkins" }
pipeline-groovy-lib = { module = "io.jenkins.plugins:pipeline-groovy-lib", version.ref = "pipeline-groovy-lib" }
