[versions]
groovy = "2.4.21"
groovy-cps = "4177.vb_203fe395445"
pipeline-unit = "1.29"
junit = "6.0.1"
codenarc = "3.6.0"

[libraries]
groovy = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
groovy-cps = { module = "com.cloudbees:groovy-cps", version.ref = "groovy-cps" }
pipeline-unit = { module = "com.lesfurets:jenkins-pipeline-unit", version.ref = "pipeline-unit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
codenarc = { module = "org.codenarc:CodeNarc", version.ref = "codenarc" }
