# Copyright 2026 Hamid Gholami
# SPDX-License-Identifier: Apache-2.0

cpu: 2
memory: 4
disk: 30
arch: aarch64
runtime: docker
vmType: vz
mountType: virtiofs
autoActivate: false
kubernetes:
  enabled: false
